### ISSUE TITLE
Chrome extension is marked "not trusted" by Enhanced Safe Browsing

### ISSUE THREAD

**Issue by tyler36** [drud/ddev-browser-extension#1]
The current development of a bookmarklet (https://github.com/drud/ddev/pull/3526) might make this obsolete. However, if this extension is maintained, it would be ideal to overcome this warning. 

![image](https://user-images.githubusercontent.com/7234392/149873850-4028bd3e-c95f-4f80-b40f-2d388b2beefe.png)

"Learn more" links to the following [site ](https://support.google.com/chrome_webstore/answer/2664769?visit_id=637780784857151262-1933089044&rd=2&hl=en#10745467).

It does not seem to affect its installation or function.

## Versions
Chrome Version 97.0.4692.71 (Official Build) (64-bit)
DDEV Gitpod Launcher 0.1

**Comment by rfay** [comment]
When you provided the excellent bookmarklet, I removed this from the docs, because the bookmarklet is such a better solution. I'll see if I can remove the extension from the store.

**Comment by rfay** [comment]
I unpublished the extension, thanks!

**Comment by tyler36** [comment]
I opened the issue just to track the loose ends.

**Comment by rfay** [comment]
And I appreciate it.
